# 用户服务配置
spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# 服务端口
server:
  port: 8081

# 日志配置
logging:
  level:
    com.example: DEBUG 