server:
  port: 8082

spring:
  application:
    name: content-service
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:contentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 